title: Elmo John Gacutan 
logo: assets/img/elmo.PNG
description: To know how far I can go and never stop trying to reach my goals and achieve the things that I want to learn, I’ll keep moving forward until I will become successful through God.
#show_downloads: true
theme: jekyll-theme-minimal
