title: Elmo John Gacutan
logo: assets/img/elmo.PNG
description:" Address : #149c Lower hasmin ext. Brgy  Payatas A  Q.C
              Contact : 09369082001
              Email : John7elmo@gmail.com	"
#show_downloads: true
theme: jekyll-theme-minimal
